[
  {
    "wav": "Straightahead.mp3",
    "nameAR": "إلى الأمام مباشرة ",
    "nameRS": "Вперед",
    "nameEN": ""
  },
  {
    "wav": "Intheback.mp3",
    "nameAR": "في الخلف ",
    "nameRS": "Сзади",
    "nameEN": ""
  },
  {
    "wav": "Tothefront.mp3",
    "nameAR": "إلى الأمام ",
    "nameRS": "Спереди",
    "nameEN": ""
  },
  {
    "wav": "Inside.mp3",
    "nameAR": "داخل ",
    "nameRS": "Внутри",
    "nameEN": ""
  },
  {
    "wav": "Outside.mp3",
    "nameAR": "خارج ",
    "nameRS": "За пределами (снаружи)",
    "nameEN": ""
  },
  {
    "wav": "Here.mp3",
    "nameAR": "هنا  ",
    "nameRS": "Здесь",
    "nameEN": ""
  },
  {
    "wav": "There.mp3",
    "nameAR": "هناك  ",
    "nameRS": "Там",
    "nameEN": ""
  },
  {
    "wav": "Alongthewall.mp3",
    "nameAR": "بمحاذاة الجدار ",
    "nameRS": "Вдоль стены",
    "nameEN": ""
  },
  {
    "wav": "Near.mp3",
    "nameAR": "قريب ",
    "nameRS": "Около",
    "nameEN": ""
  },
  {
    "wav": "Far.mp3",
    "nameAR": "بعيد ",
    "nameRS": "Далеко",
    "nameEN": ""
  },
  {
    "wav": "Aroundthecorner.mp3",
    "nameAR": "قريب جداً ",
    "nameRS": "За углом",
    "nameEN": ""
  },
  {
    "wav": "Atthedesk.mp3",
    "nameAR": "على المكتب ",
    "nameRS": "За столом",
    "nameEN": ""
  },
  {
    "wav": "Intheline.mp3",
    "nameAR": "على الخط ",
    "nameRS": "В очереди",
    "nameEN": ""
  },
  {
    "wav": "Downstairs.mp3",
    "nameAR": "الطابق السفلي ",
    "nameRS": "Вниз",
    "nameEN": ""
  },
  {
    "wav": "Upstairs.mp3",
    "nameAR": "الطابق العلوي ",
    "nameRS": "Наверх",
    "nameEN": ""
  },
  {
    "wav": "Downthehall.mp3",
    "nameAR": "القاعة ",
    "nameRS": "По коридору",
    "nameEN": ""
  },
  {
    "wav": "Inbackof.mp3",
    "nameAR": "خلف ",
    "nameRS": "За ",
    "nameEN": ""
  },
  {
    "wav": "Infrontof.mp3",
    "nameAR": "أمام ",
    "nameRS": "Перед ",
    "nameEN": ""
  },
  {
    "wav": "Beside.mp3",
    "nameAR": "بجانب ",
    "nameRS": "Рядом ",
    "nameEN": ""
  },
  {
    "wav": "Firstdoorontheright.mp3",
    "nameAR": "أول باب على اليمين ",
    "nameRS": "Первая дверь справа ",
    "nameEN": ""
  },
  {
    "wav": "Atthefourthlightturnright.mp3",
    "nameAR": "انعطف يمينا عند الإشارة الضوئية الرابعة ",
    "nameRS": "На четвертом светофоре поверните направо ",
    "nameEN": ""
  },
  {
    "wav": "Doyouunderstandme.mp3",
    "nameAR": "هل تفهمني؟ ",
    "nameRS": "Вы меня понимаете? ",
    "nameEN": ""
  },
  {
    "wav": "North.mp3",
    "nameAR": "شمال ",
    "nameRS": "Север ",
    "nameEN": ""
  },
  {
    "wav": "West.mp3",
    "nameAR": "غرب ",
    "nameRS": "Запад ",
    "nameEN": ""
  },
  {
    "wav": "South.mp3",
    "nameAR": "جنوب ",
    "nameRS": "Юг ",
    "nameEN": ""
  },
  {
    "wav": "East.mp3",
    "nameAR": "شرق ",
    "nameRS": "Восток ",
    "nameEN": ""
  },
  {
    "wav": "Totheright.mp3",
    "nameAR": "إلى اليمين ",
    "nameRS": "Вправо ",
    "nameEN": ""
  },
  {
    "wav": "Totheleft.mp3",
    "nameAR": "إلى اليسار ",
    "nameRS": "Влево ",
    "nameEN": ""
  },
  {
    "wav": "Isthereanelevator.mp3",
    "nameAR": "هل يوجد مصعد؟ ",
    "nameRS": "Здесь есть лифт? ",
    "nameEN": ""
  },
  {
    "wav": "Wherearethestairs.mp3",
    "nameAR": "أين يوجد الدرج؟ ",
    "nameRS": "Где лестница? ",
    "nameEN": ""
  },
  {
    "wav": "Inwhichdirection.mp3",
    "nameAR": "في أي اتجاه؟ ",
    "nameRS": "В каком направлении? ",
    "nameEN": ""
  },
  {
    "wav": "Seconddoorontheleft.mp3",
    "nameAR": "الباب الثاني على اليسار ",
    "nameRS": "Вторая дверь слева ",
    "nameEN": ""
  },
  {
    "wav": "Atthecornerturnleft.mp3",
    "nameAR": "انعطف يسارًا عند الزاوية ",
    "nameRS": "На углу поверните налево ",
    "nameEN": ""
  }
]


